/* C header generation for a scriptc library-mode archive.
 *
 * The header is the deliverable; the shim is the convenience layer a C host
 * links once so its call sites stay readable. Both are generated from the
 * same `CSignature[]` the ABI module derives from the profile, and
 * `test/ir-audit.test.ts` checks that list against the archive's own LLVM IR
 * — so the header cannot drift from the artifact it declares.
 *
 * Style rules, all deliberate:
 *   - one declaration per line, wrapped and indented so a diff of the header
 *     reads like a diff of the API;
 *   - the marshalling rules are IN the file, as prose, because the header is
 *     what an embedder actually reads (nobody opens the profile twice);
 *   - `extern "C"` guards so a C++ host includes it directly;
 *   - no generated timestamps or absolute paths: the same profile and stem
 *     produce the same bytes, so the header is reproducible and diffable.
 */

import type { LibraryProfile } from "../library/library-profile.js";
import {
  callbackTypedef,
  declareParam,
  includeGuard,
  sinkTypedefName,
  isCIdentifier,
  prefixOf,
  signaturesOf,
  type CParam,
  type CSignature,
} from "./c-abi.js";

export interface HeaderOptions {
  /** Basename stem, used for the include guard and the emitted `#include`
   * line in the shim. Default: derived from the profile name. */
  stem?: string;
  /** Skip the explanatory prose. For a checked-in generated file whose
   * README carries the same text, or a byte-budget-sensitive embed. */
  bare?: boolean;
}

export interface GeneratedFile {
  /** File name to write. */
  name: string;
  /** Full text. */
  text: string;
}

/** A safe stem: C identifiers only, so both the file name and the guard are
 * predictable. */
export function stemOf(profile: LibraryProfile, explicit?: string): string {
  const raw = explicit ?? profile.name;
  const cleaned = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return cleaned === "" ? "scriptc_library" : cleaned;
}

/** Split a parameter list at TOP-LEVEL commas only: a function-pointer
 * parameter contains commas of its own, and splitting inside it produces a
 * prototype no compiler accepts. */
function splitParams(list: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < list.length; i++) {
    const ch = list.charAt(i);
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    else if (ch === "," && depth === 0) {
      parts.push(list.slice(start, i).trim());
      start = i + 1;
    }
  }
  const tail = list.slice(start).trim();
  if (tail.length > 0) parts.push(tail);
  return parts;
}

function wrapDeclaration(signature: string): string {
  const oneLine = signature + ";";
  if (oneLine.length <= 100) return oneLine;
  // Break at top-level parameter commas, keeping the return type and the
  // function name on the first line. Cosmetic, but a 300-column prototype is
  // unreadable in a diff.
  const open = signature.indexOf("(");
  const head = signature.slice(0, open + 1);
  const args = splitParams(signature.slice(open + 1, signature.length - 1));
  const lines: string[] = [head];
  for (let i = 0; i < args.length; i++) {
    const last = i === args.length - 1;
    lines.push("    " + args[i] + (last ? ");" : ","));
  }
  return lines.join("\n");
}

/** Reflow a doc sentence into comment lines of at most ~76 columns, so the
 * header stays readable at a normal editor width. */
function commentLines(text: string, indent: string): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = `${indent} *`;
  for (const word of words) {
    if (current.length + word.length + 1 > 76 && current !== `${indent} *`) {
      lines.push(current);
      current = `${indent} *`;
    }
    current = `${current} ${word}`;
  }
  lines.push(current);
  const first = lines[0]!;
  lines[0] = `${indent}/*` + first.slice(`${indent} *`.length);
  lines[lines.length - 1] = lines[lines.length - 1]! + " */";
  return lines;
}

function paramList(sig: CSignature): string {
  if (sig.params.length === 0) return "void";
  return sig.params.map(declareParam).join(", ");
}

function declarationOf(sig: CSignature): string {
  return `${sig.returns} ${sig.symbol}(${paramList(sig)})`;
}

function docBlock(sig: CSignature, indent: string): string[] {
  return commentLines(sig.doc, indent);
}

/** The generated header text. */
export function generateHeader(profile: LibraryProfile, options: HeaderOptions = {}): string {
  const stem = stemOf(profile, options.stem);
  const guard = includeGuard(profile, stem);
  const signatures = signaturesOf(profile);
  const out: string[] = [];

  out.push(`/* ${stem}.h — generated by @scriptc/c-embed. Do not edit.`);
  out.push(` *`);
  out.push(` * The C ABI of the scriptc library-mode archive built from`);
  out.push(` * \`${relativeProfileEntry(profile)}\` under the profile "${profile.name}".`);
  out.push(` * Regenerate with:`);
  out.push(` *   scriptc build --lib --profile <profile.json> --header`);
  out.push(` * or, without rebuilding the archive:`);
  out.push(` *   scriptc-c-embed --profile <profile.json> --out <dir>`);
  out.push(` */`);
  out.push("");
  out.push(`#ifndef ${guard}`);
  out.push(`#define ${guard}`);
  out.push("");
  out.push(`#include <stddef.h>`);
  out.push(`#include <stdint.h>`);
  out.push("");
  out.push(`#ifdef __cplusplus`);
  out.push(`extern "C" {`);
  out.push(`#endif`);
  out.push("");

  if (options.bare !== true) {
    out.push(...usagePreamble(profile));
  }

  /* Callbacks before exports: the registration function's own documentation
   * points at the channel typedefs, and a reader should meet the host's
   * obligations before the calls that exercise them. */
  const groups: readonly (readonly [CSignature["group"], string])[] = [
    ["lifecycle", "Instance lifecycle"],
    ["callbacks", "Host-callback channels"],
    ["exports", `Exports (${profile.exports.length})`],
    ["identity", "Build identity"],
  ] as const;

  for (const [group, title] of groups) {
    const groupSigs = signatures.filter((s) => s.group === group);
    if (groupSigs.length === 0) continue;
    if (group === "callbacks") {
      out.push(`/* ── ${title} ─────────────────────────────────────────────────────────`);
      out.push(` *`);
      out.push(` * The compiled code calls these; the host implements and registers them`);
      out.push(` * with ${profile.callbackRegisterSymbol ?? "<register>"}. Declaration order in the`);
      out.push(` * profile IS the runtime slot order. A channel that was never registered`);
      out.push(` * traps with SC4025 when the compiled code calls it.`);
      out.push(` */`);
      out.push("");
      for (const cb of profile.callbacks) {
        const typedef = callbackTypedef(cb);
        if (!isCIdentifier(typedef.name)) continue;
        out.push(`/* channel "${cb.name}" */`);
        out.push(typedef.text);
      }
      out.push("");
    } else {
      out.push(`/* ── ${title} ───────────────────────────────────────────────────────── */`);
      out.push("");
      if (group === "lifecycle") {
        out.push(`/* The panic-sink handler: structured trap-teaching bytes plus the source`);
        out.push(` * address slot (0 when the trap carries none). It is called from the`);
        out.push(` * thread that trapped, so it must not call back into the library. */`);
        out.push(`typedef void (*${sinkTypedefName(profile)})(void *ctx, const uint8_t *msg, size_t len, uint64_t addr);`);
        out.push("");
      }
    }
    for (const sig of groupSigs) {
      out.push(...docBlock(sig, ""));
      out.push(wrapDeclaration(declarationOf(sig)));
      out.push("");
    }
  }

  out.push(`#ifdef __cplusplus`);
  out.push(`} /* extern "C" */`);
  out.push(`#endif`);
  out.push("");
  out.push(`#endif /* ${guard} */`);
  out.push("");
  return out.join("\n");
}

/** The profile's entry as an embedder-relative path (never an absolute one:
 * a generated header that leaks a build machine's paths is a reproducibility
 * bug). */
function relativeProfileEntry(profile: LibraryProfile): string {
  const entry = profile.entry.replace(/\\/g, "/");
  const at = entry.lastIndexOf("/");
  return at < 0 ? entry : entry.slice(at + 1);
}

/** The prose an embedder needs and would otherwise have to reconstruct from
 * the profile. Kept in the header on purpose: this is the file people read. */
function usagePreamble(profile: LibraryProfile): string[] {
  const out: string[] = [];
  const autoReset = profile.resultResetSymbol === null;
  out.push(`/*`);
  out.push(` * MARSHALLING`);
  out.push(` *`);
  out.push(` *   f64      double`);
  out.push(` *   bool     uint8_t (0/1)`);
  out.push(` *   u8/u32/i32/i64/u64   the matching <stdint.h> type`);
  out.push(` *   string   const uint8_t *ptr, size_t len   — UTF-8, NOT NUL-terminated`);
  out.push(` *   bytes    const uint8_t *ptr, size_t len   — raw bytes`);
  out.push(` *`);
  out.push(` * A \`string\` or \`bytes\` RETURN arrives through two out-parameters:`);
  out.push(` * \`const uint8_t **out, size_t *out_len\`. The wrapper points \`*out\` at the`);
  out.push(` * library's own arena and writes the length; it does NOT copy into a host`);
  out.push(` * buffer. Copy what you keep before the next call (or declare a result`);
  out.push(` * reset symbol and keep it until you reset). A string's bytes are`);
  out.push(` * NUL-terminated after \`*out_len\`, but treat \`out_len\` as authoritative:`);
  out.push(` * a string may legitimately contain NUL bytes.`);
  out.push(` *`);
  out.push(` * MEMORY`);
  out.push(` *`);
  if (autoReset) {
    out.push(` *   Every export call resets the result arena on entry, so a pointer a`);
    out.push(` *   previous call returned is INVALID once the next export call begins —`);
    out.push(` *   including the pointers written through \`out\`. Copy what you keep.`);
    out.push(` *   (The generated shim does exactly that for you.)`);
  } else {
    out.push(` *   Results accumulate: pointers stay valid until you call`);
    out.push(` *   \`${profile.resultResetSymbol}\`. That is this profile's declared posture, and it is`);
    out.push(` *   what makes holding several results at once safe.`);
  }
  out.push(` *`);
  out.push(` * EXCEPTIONS`);
  out.push(` *`);
  out.push(` *   An exception that escapes an export is delivered to the registered panic`);
  out.push(` *   sink and the call returns a zero value. Register a sink or a trap is`);
  out.push(` *   fatal to the process.`);
  out.push(` *`);
  if (profile.localizeRuntime) {
    out.push(` * INSTANCES`);
    out.push(` *`);
    out.push(` *   This profile localizes the runtime, so several archives with distinct`);
    out.push(` *   prefixes can be linked into one process without symbol collisions.`);
    out.push(` *`);
  }
  if (profile.instancePerThread) {
    out.push(` * THREADS`);
    out.push(` *`);
    out.push(` *   This profile is thread-instanced: every mutable static is thread-local,`);
    out.push(` *   so each thread that calls \`${profile.initSymbol}\` gets an independent instance.`);
    out.push(` *   Two threads share no program state, and an export must not be called from`);
    out.push(` *   a second thread while the first is inside one (per-thread, not per-call).`);
    out.push(` *`);
  } else {
    out.push(` * THREADS`);
    out.push(` *`);
    out.push(` *   One instance per linked archive. Calls are not re-entrant across threads:`);
    out.push(` *   serialize them (or build an \`instance_per_thread\` profile).`);
    out.push(` *`);
  }
  out.push(` */`);
  out.push("");
  return out;
}

/** True when an export moves a buffer in or out, and therefore wants a
 * convenience wrapper. */
export function carriesBuffer(sig: CSignature): boolean {
  if (sig.group !== "exports") return false;
  for (const p of sig.params) {
    if (p.name === "out") return true;
  }
  return false;
}

/** The `-shim.c` file: the same surface, plus a convenience wrapper for each
 * export that carries a buffer, so an embedder does not hand-roll the
 * out-parameter dance at every call site.
 *
 * Only emitted when the profile has buffer traffic: a scalars-only library
 * needs no shim, and generating an empty one would be noise. */
export function generateShim(profile: LibraryProfile, options: HeaderOptions = {}): string | null {
  const stem = stemOf(profile, options.stem);
  const buffered = signaturesOf(profile).filter(carriesBuffer);
  if (buffered.length === 0) return null;
  const prefix = prefixOf(profile);

  const out: string[] = [];
  out.push(`/* ${stem}-shim.c — generated by @scriptc/c-embed. Do not edit.`);
  out.push(` *`);
  out.push(` * Heap-allocating wrappers for the buffer-carrying exports, so a host call`);
  out.push(` * site reads like a normal function call. Each wrapper copies the result out`);
  out.push(` * of the library's arena into a host-owned buffer the caller frees with`);
  out.push(` * \`${prefix}shim_free\`.`);
  out.push(` */`);
  out.push("");
  out.push(`#include "${stem}-shim.h"`);
  out.push("");
  out.push(`#include <stdlib.h>`);
  out.push("");
  out.push(`uint8_t *${prefix}shim_alloc(size_t len) {`);
  out.push(`  return (uint8_t *)malloc(len + 1);`);
  out.push(`}`);
  out.push("");
  out.push(`void ${prefix}shim_free(uint8_t *buffer) {`);
  out.push(`  free(buffer);`);
  out.push(`}`);
  out.push("");

  for (const sig of buffered) {
    out.push(...shimWrapper(sig, prefix));
  }
  return out.join("\n");
}

/** The wrapper name for an export symbol: prefix + `shim_` + the symbol with
 * its own prefix removed, so `kt_add` becomes `kt_shim_add`. */
function shimName(prefix: string, symbol: string): string {
  return `${prefix}shim_${symbol.startsWith(prefix) ? symbol.slice(prefix.length) : symbol}`;
}

/** Value parameters (everything except the out-parameter pair). */
function valueParams(sig: CSignature): CParam[] {
  return sig.params.filter((p) => p.name !== "out" && p.name !== "out_len");
}

function shimWrapper(sig: CSignature, prefix: string): string[] {
  const out: string[] = [];
  const values = valueParams(sig);
  const args = values.map(declareParam).join(", ");
  const passes = values.map((p) => p.name).join(", ");
  const name = shimName(prefix, sig.symbol);
  const emitsBuffer = sig.returns === "void" && sig.params.some((p) => p.name === "out");

  if (!emitsBuffer) {
    out.push(`/* Wraps ${sig.symbol}. */`);
    out.push(`${sig.returns} ${name}(${args === "" ? "void" : args}) {`);
    out.push(`  return ${sig.symbol}(${passes});`);
    out.push(`}`);
    out.push("");
    return out;
  }

  // Buffer out: call into the arena, then COPY into a host-owned buffer.
  // The copy is the whole point of the shim: the library's pointer dies with
  // the next export call, and a host that stored it would read freed memory.
  const callArgs = [...values.map((p) => p.name), "&borrowed", "out_len"].join(", ");
  out.push(`/* Wraps ${sig.symbol}: copies the result out of the library's arena into a`);
  out.push(` * host-owned buffer the caller frees with ${prefix}shim_free. Sets *out_len`);
  out.push(` * to the byte length. */`);
  out.push(`uint8_t *${name}(${args === "" ? "" : args + ", "}size_t *out_len) {`);
  out.push(`  const uint8_t *borrowed = NULL;`);
  out.push(`  ${sig.symbol}(${callArgs});`);
  out.push(`  uint8_t *buffer = ${prefix}shim_alloc(*out_len);`);
  out.push(`  if (buffer == NULL) { *out_len = 0; return NULL; }`);
  out.push(`  for (size_t i = 0; i < *out_len; i++) buffer[i] = borrowed[i];`);
  out.push(`  buffer[*out_len] = 0;`);
  out.push(`  return buffer;`);
  out.push(`}`);
  out.push("");
  return out;
}

/** The shim's header: the extra prototypes only. */
export function generateShimHeader(profile: LibraryProfile, options: HeaderOptions = {}): string | null {
  if (generateShim(profile, options) === null) return null;
  const stem = stemOf(profile, options.stem);
  const guard = includeGuard(profile, `${stem}_shim`);
  const prefix = prefixOf(profile);
  const buffered = signaturesOf(profile).filter(carriesBuffer);
  const out: string[] = [];
  out.push(`/* ${stem}-shim.h — generated by @scriptc/c-embed. Do not edit. */`);
  out.push("");
  out.push(`#ifndef ${guard}`);
  out.push(`#define ${guard}`);
  out.push("");
  out.push(`#include "${stem}.h"`);
  out.push("");
  out.push(`#ifdef __cplusplus`);
  out.push(`extern "C" {`);
  out.push(`#endif`);
  out.push("");
  out.push(`/* Allocate/free host-owned buffers. ${prefix}shim_free is free(3). */`);
  out.push(`uint8_t *${prefix}shim_alloc(size_t len);`);
  out.push(`void ${prefix}shim_free(uint8_t *buffer);`);
  out.push("");
  for (const sig of buffered) {
    const args = valueParams(sig).map(declareParam).join(", ");
    const name = shimName(prefix, sig.symbol);
    const emitsBuffer = sig.returns === "void" && sig.params.some((p) => p.name === "out");
    const returns = emitsBuffer ? "uint8_t *" : sig.returns;
    const params = emitsBuffer
      ? args === ""
        ? "size_t *out_len"
        : `${args}, size_t *out_len`
      : args === ""
        ? "void"
        : args;
    out.push(`${returns}${returns.endsWith("*") ? "" : " "}${name}(${params});`);
  }
  out.push("");
  out.push(`#ifdef __cplusplus`);
  out.push(`} /* extern "C" */`);
  out.push(`#endif`);
  out.push("");
  out.push(`#endif /* ${guard} */`);
  out.push("");
  return out.join("\n");
}

/** The JSON descriptor: the same surface for non-C embedders (Zig, Rust,
 * Python ctypes, a build system that wants to generate its own binding).
 * Deliberately mirrors the field names the header uses. */
export function generateDescriptor(profile: LibraryProfile, options: HeaderOptions = {}): string {
  const stem = stemOf(profile, options.stem);
  const document = {
    schema: "scriptc.c-embed.v1",
    profile: profile.name,
    stem: stem,
    entry: relativeProfileEntry(profile),
    prefix: profile.prefix,
    libraries: {
      localize_runtime: profile.localizeRuntime,
      instance_per_thread: profile.instancePerThread,
    },
    results: profile.resultResetSymbol === null ? "reset-per-call" : "accumulate",
    imports: ["<stddef.h>", "<stdint.h>"],
    signatures: signaturesOf(profile).map((sig) => ({
      symbol: sig.symbol,
      group: sig.group,
      returns: sig.returns,
      params: sig.params.map((p) => ({ name: p.name, type: p.type, class: p.cls })),
      doc: sig.doc,
    })),
    callbacks: profile.callbacks.map((cb) => {
      const typedef = callbackTypedef(cb);
      return { name: cb.name, typedef: typedef.name, text: typedef.text };
    }),
  };
  return JSON.stringify(document, null, 2) + "\n";
}

/** A CMake fragment that imports the archive and exposes the header and the
 * optional shim as one interface target:
 *
 *   add_subdirectory(embed)
 *   target_link_libraries(my_app PRIVATE scriptc::conformance_buffers)
 *
 * The archive path is a variable (`SCRIPT_EMBED_ARCHIVE`) rather than a baked
 * absolute path, so the fragment stays portable and reproducible; a host sets
 * it (or relies on the default, which is the file name beside the header). */
export function generateCMake(profile: LibraryProfile, options: HeaderOptions = {}): string {
  const stem = stemOf(profile, options.stem);
  const target = `scriptc::${stem}`;
  const hasShim = generateShim(profile, options) !== null;
  const out: string[] = [];
  out.push(`# ${stem}.cmake — generated by @scriptc/c-embed. Do not edit.`);
  out.push(`#`);
  out.push(`# Import the scriptc library-mode archive and expose its C surface:`);
  out.push(`#`);
  out.push(`#   set(SCRIPT_EMBED_ARCHIVE "\${CMAKE_CURRENT_LIST_DIR}/lib.lib.a")`);
  out.push(`#   include("\${CMAKE_CURRENT_LIST_DIR}/${stem}.cmake")`);
  out.push(`#   target_link_libraries(my_app PRIVATE ${target})`);
  out.push(``);
  out.push(`if(NOT DEFINED SCRIPT_EMBED_ARCHIVE)`);
  out.push(`  set(SCRIPT_EMBED_ARCHIVE "\${CMAKE_CURRENT_LIST_DIR}/lib.lib.a")`);
  out.push(`endif()`);
  out.push(``);
  out.push(`add_library(${stem}_archive STATIC IMPORTED)`);
  out.push(`set_target_properties(${stem}_archive PROPERTIES IMPORTED_LOCATION "\${SCRIPT_EMBED_ARCHIVE}")`);
  out.push(``);
  out.push(`add_library(${target} INTERFACE IMPORTED)`);
  out.push(`target_link_libraries(${target} INTERFACE ${stem}_archive)`);
  out.push(`target_include_directories(${target} INTERFACE "\${CMAKE_CURRENT_LIST_DIR}")`);
  if (hasShim) {
    out.push(``);
    out.push(`# The shim copies arena results into host-owned buffers. A host that`);
    out.push(`# wants it compiles ${stem}-shim.c into its own target:`);
    out.push(`#   target_sources(my_app PRIVATE "\${CMAKE_CURRENT_LIST_DIR}/${stem}-shim.c")`);
  }
  out.push(``);
  return out.join("\n");
}

/** Everything to write for a profile: the header, the descriptor, the CMake
 * fragment, and the shim pair when the profile moves buffers. */
export function generateAll(profile: LibraryProfile, options: HeaderOptions = {}): GeneratedFile[] {
  const stem = stemOf(profile, options.stem);
  const files: GeneratedFile[] = [
    { name: `${stem}.h`, text: generateHeader(profile, options) },
    { name: `${stem}.c-embed.json`, text: generateDescriptor(profile, options) },
    { name: `${stem}.cmake`, text: generateCMake(profile, options) },
  ];
  const shim = generateShim(profile, options);
  const shimHeader = generateShimHeader(profile, options);
  if (shim !== null && shimHeader !== null) {
    files.push({ name: `${stem}-shim.h`, text: shimHeader });
    files.push({ name: `${stem}-shim.c`, text: shim });
  }
  return files;
}
